name 'coetzeer-puppetsuite'
version '0.1.0'

author ''
license ''
dependency 'puppetlabs/puppetdb', '3.0.1'
dependency 'puppetlabs/inifile', '1.1.0'
dependency 'puppetlabs/apache', '1.0.1'
dependency 'hawknewton/pulp', '0.1.0'
dependency 'haraldsk/nfs', '1.1.1'
dependency 'stahnma/epel', '0.1.0'
